// pages/league.js — League Predictions: a fast, digestible league-wide view
// of the model's season projections. Unlike the Season Simulator (which is
// where a user configures and runs a simulation), this page auto-loads a
// default projection and focuses on answering "what does the model expect
// across the whole league right now" — strongest teams, the projected
// playoff picture, full standings, and the teams closest to the playoff
// cutoff line. It reuses the exact same `simulate_season` tool and the same
// shared rendering components as the Season Simulator; no simulation logic
// lives here.

import { getSeasonSimulation } from "../api.js";
import { fetchTeams } from "../components/teamSelect.js";
import { renderLeagueSummaryCard } from "../components/leagueSummary.js";
import { renderPlayoffField } from "../components/playoffField.js";

export const meta = {
  title: "League Predictions",
  subtitle: "A league-wide read of the model's projections: strongest teams, the projected playoff picture, and full standings.",
};

// Same validated seasons the Season Simulator exposes (src/simulate_season.py's
// own VALIDATION_SEASONS). 2025 is the default so the page shows the current
// season's projection immediately without any input from the user.
const SEASON_OPTIONS = [2025, 2024, 2023];
const DEFAULT_SEASON = 2025;

// Fixed at the Season Simulator's own default. This page is an overview, not
// a configuration surface, so the simulation-count control is deliberately
// not exposed here — a user who wants to tune it uses Season Simulator.
const N_SIMULATIONS = 1000;

// How many teams to surface in "Closest to the playoff cutoff", derived
// transparently from direct_playoff_probability rather than an invented
// narrative threshold.
const CUTOFF_WATCH_COUNT = 6;

export function render(container, ctx = {}) {
  container.innerHTML = `
    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>About this page</h2>
        </div>
      </div>
      <p>
        This page shows the production model's current season-long projection for
        every team at once, generated by the same Monte Carlo season simulation
        used on the Season Simulator page. It loads automatically below using
        ${N_SIMULATIONS.toLocaleString()} simulations for the selected season.
        These are <strong>model projections, not guaranteed outcomes</strong> —
        want to change the simulation count, or compare seasons side by side?
        <button class="link-btn" id="league-goto-simulator">Open Season Simulator ▸</button>
      </p>
    </div>

    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>Projection season</h2>
          <p class="card-subtitle">Switch seasons to instantly compare projections — the underlying model result is cached after its first calculation.</p>
        </div>
      </div>
      <div class="grid-2">
        <div class="field">
          <label for="league-season-select">Season</label>
          <div class="select-wrap">
            <select class="select" id="league-season-select">
              ${SEASON_OPTIONS.map(
                (s) => `<option value="${s}" ${s === DEFAULT_SEASON ? "selected" : ""}>${s}-${String(s + 1).slice(-2)}</option>`
              ).join("")}
            </select>
          </div>
        </div>
        <div style="display:flex; align-items:flex-end;">
          <button class="btn" id="league-reload-btn">Reload projections</button>
        </div>
      </div>
      <span id="league-status" class="text-muted"></span>
      <div id="league-error-mount" class="mt-1"></div>
    </div>

    <div id="league-result-mount"></div>
  `;

  container.querySelector("#league-goto-simulator").addEventListener("click", () => {
    if (ctx.navigate) ctx.navigate("/simulator");
  });

  const seasonSelect = container.querySelector("#league-season-select");
  const reloadBtn = container.querySelector("#league-reload-btn");

  seasonSelect.addEventListener("change", () => {
    loadProjection(container, ctx, Number(seasonSelect.value));
  });
  reloadBtn.addEventListener("click", () => {
    loadProjection(container, ctx, Number(seasonSelect.value));
  });

  // Auto-load the default season immediately — this page is meant to be a
  // fast overview, not something the user has to configure first.
  loadProjection(container, ctx, DEFAULT_SEASON);
}

// ---------------------------------------------------------------------------
// Load + orchestrate
// ---------------------------------------------------------------------------

async function loadProjection(container, ctx, season) {
  const statusEl = container.querySelector("#league-status");
  const errorMount = container.querySelector("#league-error-mount");
  const resultMount = container.querySelector("#league-result-mount");
  const reloadBtn = container.querySelector("#league-reload-btn");

  errorMount.innerHTML = "";
  reloadBtn.disabled = true;
  statusEl.textContent =
    "Loading model projections — this may take up to a minute the first time this session (the model replays the full season history once, then every load is fast).";
  resultMount.innerHTML = renderResultSkeleton();

  let res;
  try {
    res = await getSeasonSimulation({ season, nSimulations: N_SIMULATIONS });
  } catch (err) {
    reloadBtn.disabled = false;
    statusEl.textContent = "";
    resultMount.innerHTML = "";
    errorMount.innerHTML = errorBanner(`Network error while contacting the API: ${err.message}`);
    return;
  }

  reloadBtn.disabled = false;
  statusEl.textContent = "";

  if (!res.ok || res.data?.status !== "success") {
    resultMount.innerHTML = "";
    errorMount.innerHTML = errorBanner(
      res.data?.error?.message || "The league projection request failed. Please try again."
    );
    return;
  }

  const projection = res.data.data.projection;
  const teams = await fetchTeams().catch(() => []);
  resultMount.innerHTML = renderResults(projection, teams);
  wireResultInteractions(resultMount, ctx);
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function renderResultSkeleton() {
  return `
    <div class="card fade-in">
      <div class="stat-grid">
        ${Array(4).fill('<div class="skeleton" style="height:70px;"></div>').join("")}
      </div>
    </div>
    <div class="card fade-in">
      <div class="skeleton" style="height:220px;"></div>
    </div>
    <div class="card fade-in">
      <div class="skeleton" style="height:280px;"></div>
    </div>
  `;
}

function errorBanner(message) {
  return `<div class="error-banner">⚠ ${escapeHtml(message)}</div>`;
}

function renderResults(projection, teams) {
  const teamById = new Map(teams.map((t) => [t.team_id, t]));
  const east = projection.projected_standings
    .filter((r) => r.conference === "East")
    .slice()
    .sort((a, b) => b.mean_wins - a.mean_wins);
  const west = projection.projected_standings
    .filter((r) => r.conference === "West")
    .slice()
    .sort((a, b) => b.mean_wins - a.mean_wins);

  return `
    ${renderLeagueSummaryCard(projection.league_summary, teamById, projection.season, projection.n_simulations)}
    ${renderPlayoffField(projection.projected_seedings, teamById, {
      title: "Projected playoff picture",
      subtitle: "The single most likely team to occupy each direct-playoff seed slot (top 6 per conference). Click a team to open Team Explorer.",
      clickableTeams: true,
    })}
    ${renderCutoffWatch(east, west, teamById)}
    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>Projected standings</h2>
          <p class="card-subtitle">All 30 teams, ranked by projected mean wins within their conference. Click a team to open Team Explorer.</p>
        </div>
      </div>
      <div class="grid-2">
        ${renderStandingsTable("Eastern Conference", east, teamById)}
        ${renderStandingsTable("Western Conference", west, teamById)}
      </div>
    </div>
  `;
}

/**
 * "Closest to the playoff cutoff" — the teams whose direct_playoff_probability
 * is nearest to 50%, i.e. the model is least certain whether they finish in
 * the top 6 of their conference or not. Purely a proximity sort on a field
 * the backend already returns; no new statistic is invented.
 */
function renderCutoffWatch(east, west, teamById) {
  const rankByTeam = new Map();
  east.forEach((row, index) => rankByTeam.set(row.teamId, index + 1));
  west.forEach((row, index) => rankByTeam.set(row.teamId, index + 1));

  const all = [...east, ...west]
    .filter((row) => row.direct_playoff_probability != null)
    .slice()
    .sort(
      (a, b) =>
        Math.abs(a.direct_playoff_probability - 0.5) - Math.abs(b.direct_playoff_probability - 0.5)
    )
    .slice(0, CUTOFF_WATCH_COUNT);

  if (!all.length) return "";

  return `
    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>Teams to watch</h2>
          <p class="card-subtitle">
            The teams whose projected direct-playoff odds are closest to 50% — where the model is
            least certain whether they land in the top 6 of their conference.
          </p>
        </div>
      </div>
      <div class="stat-grid">
        ${all
          .map((row) => {
            const oddsColor = playoffOddsColor(row.direct_playoff_probability);
            const team = teamById.get(row.teamId);
            return `
              <div class="stat-tile" data-team-link="${row.teamId}" style="cursor:pointer;">
                <div class="stat-label">${row.conference} · #${rankByTeam.get(row.teamId)} projected</div>
                <div class="stat-value" style="font-size:1rem;">${escapeHtml(team?.full_name || row.teamId)}</div>
                <div class="text-muted" style="font-size:0.76rem; margin-bottom:0.3rem;">${row.mean_wins.toFixed(1)} mean wins</div>
                <div class="compare-track">
                  <div class="compare-fill home" style="width:${row.direct_playoff_probability * 100}%; background:${oddsColor};"></div>
                </div>
                <div class="text-muted" style="font-size:0.72rem; margin-top:0.2rem;">${(row.direct_playoff_probability * 100).toFixed(0)}% direct-playoff odds</div>
              </div>
            `;
          })
          .join("")}
      </div>
    </div>
  `;
}

function renderStandingsTable(title, rows, teamById) {
  return `
    <div>
      <div class="section-title">${title}</div>
      <table style="width:100%; border-collapse:collapse; font-size:0.84rem;">
        <thead>
          <tr style="text-align:left; color:var(--text-secondary); font-size:0.72rem; text-transform:uppercase; letter-spacing:0.04em;">
            <th style="padding:0.4rem 0.3rem;">#</th>
            <th style="padding:0.4rem 0.3rem;">Team</th>
            <th style="padding:0.4rem 0.3rem; text-align:right;">Mean wins</th>
            <th style="padding:0.4rem 0.3rem; text-align:right;">Playoff odds</th>
          </tr>
        </thead>
        <tbody>
          ${rows
            .map((row, index) => {
              const team = teamById.get(row.teamId);
              const oddsColor = playoffOddsColor(row.direct_playoff_probability);
              return `
                <tr data-team-link="${row.teamId}" style="border-top:1px solid var(--border); cursor:pointer;">
                  <td style="padding:0.5rem 0.3rem; color:var(--text-secondary);">${index + 1}</td>
                  <td style="padding:0.5rem 0.3rem; font-weight:600;">${escapeHtml(team?.full_name || row.teamId)}</td>
                  <td style="padding:0.5rem 0.3rem; text-align:right;">${row.mean_wins.toFixed(1)}</td>
                  <td style="padding:0.5rem 0.3rem;">
                    <div style="display:flex; align-items:center; gap:0.5rem; justify-content:flex-end;">
                      <span>${(row.direct_playoff_probability * 100).toFixed(0)}%</span>
                      <div class="compare-track" style="width:60px;">
                        <div class="compare-fill home" style="width:${row.direct_playoff_probability * 100}%; background:${oddsColor};"></div>
                      </div>
                    </div>
                  </td>
                </tr>
              `;
            })
            .join("")}
        </tbody>
      </table>
    </div>
  `;
}

function playoffOddsColor(probability) {
  if (probability >= 0.75) return "var(--positive)";
  if (probability >= 0.25) return "var(--warning)";
  return "var(--text-muted)";
}

// ---------------------------------------------------------------------------
// Interaction wiring
// ---------------------------------------------------------------------------

function wireResultInteractions(resultMount, ctx) {
  if (!ctx.navigate) return;
  resultMount.querySelectorAll("[data-team-link]").forEach((el) => {
    el.addEventListener("click", () => {
      ctx.navigate("/teams", { team: el.dataset.teamLink });
    });
  });
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (c) => (
    { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
  ));
}
