// pages/league.js — League Predictions: a fast, digestible league-wide view
// of the model's season projections. Unlike the Season Simulator (which is
// where a user configures and runs a simulation), this page auto-loads a
// default projection and focuses on answering "what does the model expect
// across the whole league right now" — strongest teams, the projected
// playoff picture, full standings, and the teams closest to the playoff
// cutoff line. It reuses the exact same `simulate_season` tool and the same
// shared rendering components as the Season Simulator; no simulation logic
// lives here.

import { getSeasonSimulation } from "../api.js";
import { fetchTeams } from "../components/teamSelect.js";
import { renderLeagueSummaryCard } from "../components/leagueSummary.js";
import { renderPlayoffField } from "../components/playoffField.js";
import { teamColor } from "../teamColors.js";
import { clashingPair, teamSlabStyle } from "../colorInk.js";

export const meta = {
  title: "League Predictions",
  subtitle: "A league-wide read of the model's projections: strongest teams, the projected playoff picture, and full standings.",
};

// Same validated seasons the Season Simulator exposes (src/simulate_season.py's
// own VALIDATION_SEASONS). 2025 is the default so the page shows the current
// season's projection immediately without any input from the user.
const SEASON_OPTIONS = [2025, 2024, 2023];
const DEFAULT_SEASON = 2025;

// Fixed at the Season Simulator's own default. This page is an overview, not
// a configuration surface, so the simulation-count control is deliberately
// not exposed here — a user who wants to tune it uses Season Simulator.
const N_SIMULATIONS = 1000;

// How many teams to surface in "Closest to the playoff cutoff", derived
// transparently from direct_playoff_probability rather than an invented
// narrative threshold.
const CUTOFF_WATCH_COUNT = 6;

// "Headline of the day" story thresholds, applied to the gap in projected
// mean wins between the league's #1 and #2 teams (see web/DESIGN-BRIEF.md).
const RUNAWAY_LEAD_MIN = 4.0; // lead >= 4.0 wins → "RUNAWAY"
const DOGFIGHT_LEAD_BELOW = 1.0; // lead < 1.0 wins → "DOGFIGHT AT THE TOP"

export function render(container, ctx = {}) {
  container.innerHTML = `
    <div id="league-headline-mount"></div>

    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>About this page</h2>
        </div>
      </div>
      <p>
        This page shows the production model's current season-long projection for
        every team at once, generated by the same Monte Carlo season simulation
        used on the Season Simulator page. It loads automatically below using
        ${N_SIMULATIONS.toLocaleString()} simulations for the selected season.
        These are <strong>model projections, not guaranteed outcomes</strong> —
        want to change the simulation count, or compare seasons side by side?
        <button class="link-btn" id="league-goto-simulator">Open Season Simulator ▸</button>
      </p>
    </div>

    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>Projection season</h2>
          <p class="card-subtitle">Switch seasons to instantly compare projections — the underlying model result is cached after its first calculation.</p>
        </div>
      </div>
      <div class="grid-2">
        <div class="field">
          <label for="league-season-select">Season</label>
          <div class="select-wrap">
            <select class="select" id="league-season-select">
              ${SEASON_OPTIONS.map(
                (s) => `<option value="${s}" ${s === DEFAULT_SEASON ? "selected" : ""}>${s}-${String(s + 1).slice(-2)}</option>`
              ).join("")}
            </select>
          </div>
        </div>
        <div style="display:flex; align-items:flex-end;">
          <button class="btn" id="league-reload-btn">Reload projections</button>
        </div>
      </div>
      <span id="league-status" class="text-muted"></span>
      <div id="league-error-mount" class="mt-1"></div>
    </div>

    <div id="league-result-mount"></div>
  `;

  container.querySelector("#league-goto-simulator").addEventListener("click", () => {
    if (ctx.navigate) ctx.navigate("/simulator");
  });

  const seasonSelect = container.querySelector("#league-season-select");
  const reloadBtn = container.querySelector("#league-reload-btn");

  seasonSelect.addEventListener("change", () => {
    loadProjection(container, ctx, Number(seasonSelect.value));
  });
  reloadBtn.addEventListener("click", () => {
    loadProjection(container, ctx, Number(seasonSelect.value));
  });

  // Auto-load the default season immediately — this page is meant to be a
  // fast overview, not something the user has to configure first.
  loadProjection(container, ctx, DEFAULT_SEASON);
}

// ---------------------------------------------------------------------------
// Load + orchestrate
// ---------------------------------------------------------------------------

async function loadProjection(container, ctx, season) {
  const statusEl = container.querySelector("#league-status");
  const errorMount = container.querySelector("#league-error-mount");
  const resultMount = container.querySelector("#league-result-mount");
  const reloadBtn = container.querySelector("#league-reload-btn");
  const headlineMount = container.querySelector("#league-headline-mount");

  errorMount.innerHTML = "";
  reloadBtn.disabled = true;
  headlineMount.innerHTML = renderHeadlineSkeleton();
  statusEl.textContent =
    "Loading model projections — this may take up to a minute the first time this session (the model replays the full season history once, then every load is fast).";
  resultMount.innerHTML = renderResultSkeleton();

  let res;
  try {
    res = await getSeasonSimulation({ season, nSimulations: N_SIMULATIONS });
  } catch (err) {
    reloadBtn.disabled = false;
    statusEl.textContent = "";
    resultMount.innerHTML = "";
    headlineMount.innerHTML = "";
    errorMount.innerHTML = errorBanner(`Network error while contacting the API: ${err.message}`);
    return;
  }

  reloadBtn.disabled = false;
  statusEl.textContent = "";

  if (!res.ok || res.data?.status !== "success") {
    resultMount.innerHTML = "";
    headlineMount.innerHTML = "";
    errorMount.innerHTML = errorBanner(
      res.data?.error?.message || "The league projection request failed. Please try again."
    );
    return;
  }

  const projection = res.data.data.projection;
  const teams = await fetchTeams().catch(() => []);
  const teamById = new Map(teams.map((t) => [t.team_id, t]));
  headlineMount.innerHTML = renderHeadlineOfTheDay(projection, teamById);
  resultMount.innerHTML = renderResults(projection, teams);
  wireResultInteractions(headlineMount, ctx);
  wireResultInteractions(resultMount, ctx);
}

// ---------------------------------------------------------------------------
// Rendering
// ---------------------------------------------------------------------------

function renderHeadlineSkeleton() {
  return `
    <div class="card clipping front-page fade-in" aria-hidden="true">
      <div class="skeleton" style="height:28px; width:220px;"></div>
      <div class="skeleton mt-2" style="height:72px; width:70%;"></div>
      <div class="skeleton mt-1" style="height:18px; width:55%;"></div>
    </div>
  `;
}

function renderResultSkeleton() {
  return `
    <div class="card fade-in">
      <div class="stat-grid">
        ${Array(4).fill('<div class="skeleton" style="height:70px;"></div>').join("")}
      </div>
    </div>
    <div class="card fade-in">
      <div class="skeleton" style="height:220px;"></div>
    </div>
    <div class="card fade-in">
      <div class="skeleton" style="height:280px;"></div>
    </div>
  `;
}

function errorBanner(message) {
  return `<div class="error-banner">⚠ ${escapeHtml(message)}</div>`;
}

function renderResults(projection, teams) {
  const teamById = new Map(teams.map((t) => [t.team_id, t]));
  const east = projection.projected_standings
    .filter((r) => r.conference === "East")
    .slice()
    .sort((a, b) => b.mean_wins - a.mean_wins);
  const west = projection.projected_standings
    .filter((r) => r.conference === "West")
    .slice()
    .sort((a, b) => b.mean_wins - a.mean_wins);

  return `
    ${renderLeagueSummaryCard(projection.league_summary, teamById, projection.season, projection.n_simulations)}
    ${renderPlayoffField(projection.projected_seedings, teamById, {
      title: "Projected playoff picture",
      subtitle: "The single most likely team to occupy each direct-playoff seed slot (top 6 per conference). Click a team to open Team Explorer.",
      clickableTeams: true,
    })}
    ${renderCutoffWatch(east, west, teamById)}
    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>Projected standings</h2>
          <p class="card-subtitle">All 30 teams, ranked by projected mean wins within their conference. Click a team to open Team Explorer.</p>
        </div>
      </div>
      <div class="grid-2">
        ${renderStandingsTable("Eastern Conference", east, teamById)}
        ${renderStandingsTable("Western Conference", west, teamById)}
      </div>
    </div>
  `;
}

/**
 * "Headline of the day": the biggest story in the projection already on the
 * page. The story is the race at the top (#1's projected-win lead over #2),
 * plus two teasers: the bubble team (direct-playoff odds closest to 50%)
 * and the basement (league_summary.worst_team). No new data is fetched.
 */
function renderHeadlineOfTheDay(projection, teamById) {
  const ranked = projection.projected_standings
    .filter((row) => typeof row.mean_wins === "number")
    .slice()
    .sort((a, b) => b.mean_wins - a.mean_wins);
  if (ranked.length < 2) return "";

  const [top, second] = ranked;
  const lead = top.mean_wins - second.mean_wins;
  const topName = fullName(teamById, top.teamId);
  const secondName = fullName(teamById, second.teamId);
  // Two teams in one headline clash rather than blend (same rule as Matchups).
  const { first: topColor, second: secondColor } = clashingPair(
    teamColor(top.teamId),
    teamColor(second.teamId)
  );
  const slab = (row) =>
    `<span class="hl-team" style="${teamSlabStyle(row === top ? topColor : secondColor)}">${escapeHtml(nickname(teamById, row.teamId))}</span>`;

  let tag;
  let headline;
  let deck;
  if (lead >= RUNAWAY_LEAD_MIN) {
    tag = "Runaway";
    headline = `${slab(top)} <span class="scrawl">run away with it</span>`;
    deck = `The ${escapeHtml(topName)} project to <strong>${top.mean_wins.toFixed(1)}</strong> wins,
      <strong>${lead.toFixed(1)}</strong> clear of the ${escapeHtml(secondName)} (<strong>${second.mean_wins.toFixed(1)}</strong>).`;
  } else if (lead < DOGFIGHT_LEAD_BELOW) {
    tag = "Dogfight";
    headline = `${slab(top)} <span class="scrawl">vs</span> ${slab(second)} <span class="scrawl">for the top</span>`;
    deck = `Just <strong>${lead.toFixed(1)}</strong> projected wins separate the ${escapeHtml(topName)}
      (<strong>${top.mean_wins.toFixed(1)}</strong>) and the ${escapeHtml(secondName)} (<strong>${second.mean_wins.toFixed(1)}</strong>).`;
  } else {
    tag = "On top";
    headline = `${slab(top)} <span class="scrawl">on top</span>`;
    deck = `The ${escapeHtml(topName)} lead the league at <strong>${top.mean_wins.toFixed(1)}</strong> projected wins,
      <strong>${lead.toFixed(1)}</strong> ahead of the ${escapeHtml(secondName)}.`;
  }

  const bubble = projection.projected_standings
    .filter((row) => typeof row.direct_playoff_probability === "number")
    .slice()
    .sort(
      (a, b) =>
        Math.abs(a.direct_playoff_probability - 0.5) - Math.abs(b.direct_playoff_probability - 0.5)
    )[0];
  const basement = projection.league_summary?.worst_team;
  const seasonLabel = `${projection.season}-${String(projection.season + 1).slice(-2)}`;

  return `
    <section class="card clipping front-page fade-in" aria-labelledby="league-headline">
      <div class="clipping-masthead">
        <span class="kicker">Headline of the day</span>
        <span class="clipping-meta">${seasonLabel} projection · ${projection.n_simulations.toLocaleString()} simulations</span>
      </div>
      <div class="front-page-grid">
        <div class="front-page-lead">
          <p class="stamp stamp--tilt front-page-tag">${tag}</p>
          <h2 class="tabloid-headline" id="league-headline">${headline}</h2>
          <p class="deck">${deck}</p>
        </div>
        <div class="front-page-teasers">
          ${
            bubble
              ? `
            <div class="teaser" data-team-link="${bubble.teamId}" role="link" tabindex="0">
              <span class="teaser-kicker">Bubble watch</span>
              <span class="teaser-team">${escapeHtml(fullName(teamById, bubble.teamId))}</span>
              <span class="teaser-stat"><strong>${(bubble.direct_playoff_probability * 100).toFixed(0)}%</strong> direct-playoff odds · ${escapeHtml(bubble.conference)}</span>
            </div>`
              : ""
          }
          ${
            basement
              ? `
            <div class="teaser" data-team-link="${basement.teamId}" role="link" tabindex="0">
              <span class="teaser-kicker">The basement</span>
              <span class="teaser-team">${escapeHtml(fullName(teamById, basement.teamId))}</span>
              <span class="teaser-stat"><strong>${basement.mean_wins.toFixed(1)}</strong> projected wins, fewest in the league</span>
            </div>`
              : ""
          }
        </div>
      </div>
    </section>
  `;
}

function fullName(teamById, teamId) {
  return teamById.get(teamId)?.full_name || `Team ${teamId}`;
}

function nickname(teamById, teamId) {
  const team = teamById.get(teamId);
  return team?.name || team?.abbreviation || `Team ${teamId}`;
}

/**
 * "Closest to the playoff cutoff" — the teams whose direct_playoff_probability
 * is nearest to 50%, i.e. the model is least certain whether they finish in
 * the top 6 of their conference or not. Purely a proximity sort on a field
 * the backend already returns; no new statistic is invented.
 */
function renderCutoffWatch(east, west, teamById) {
  const rankByTeam = new Map();
  east.forEach((row, index) => rankByTeam.set(row.teamId, index + 1));
  west.forEach((row, index) => rankByTeam.set(row.teamId, index + 1));

  const all = [...east, ...west]
    .filter((row) => row.direct_playoff_probability != null)
    .slice()
    .sort(
      (a, b) =>
        Math.abs(a.direct_playoff_probability - 0.5) - Math.abs(b.direct_playoff_probability - 0.5)
    )
    .slice(0, CUTOFF_WATCH_COUNT);

  if (!all.length) return "";

  return `
    <div class="card fade-in">
      <div class="card-header">
        <div>
          <h2>Teams to watch</h2>
          <p class="card-subtitle">
            The teams whose projected direct-playoff odds are closest to 50% — where the model is
            least certain whether they land in the top 6 of their conference.
          </p>
        </div>
      </div>
      <div class="stat-grid">
        ${all
          .map((row) => {
            const oddsColor = playoffOddsColor(row.direct_playoff_probability);
            const team = teamById.get(row.teamId);
            return `
              <div class="stat-tile watch-tile" data-team-link="${row.teamId}" role="link" tabindex="0" style="cursor:pointer;">
                <div class="stat-label">${row.conference} · #${rankByTeam.get(row.teamId)} projected</div>
                <div class="stat-value" style="font-size:1rem;">${escapeHtml(team?.full_name || row.teamId)}</div>
                <div class="text-muted" style="font-size:0.76rem; margin-bottom:0.3rem;">${row.mean_wins.toFixed(1)} mean wins</div>
                <div class="compare-track">
                  <div class="compare-fill home" style="width:${row.direct_playoff_probability * 100}%; background:${oddsColor};"></div>
                </div>
                <div class="text-muted" style="font-size:0.72rem; margin-top:0.2rem;">${(row.direct_playoff_probability * 100).toFixed(0)}% direct-playoff odds</div>
              </div>
            `;
          })
          .join("")}
      </div>
    </div>
  `;
}

function renderStandingsTable(title, rows, teamById) {
  return `
    <div>
      <div class="section-title">${title}</div>
      <table class="data-table standings-table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Team</th>
            <th scope="col" class="num">Mean wins</th>
            <th scope="col" class="num">Playoff odds</th>
          </tr>
        </thead>
        <tbody>
          ${rows
            .map((row, index) => {
              const team = teamById.get(row.teamId);
              const oddsColor = playoffOddsColor(row.direct_playoff_probability);
              const cutoffClass = index === 6 ? ' class="is-below-cutoff"' : "";
              return `
                <tr${cutoffClass} data-team-link="${row.teamId}" tabindex="0">
                  <td class="rank">${index + 1}</td>
                  <td class="team">${escapeHtml(team?.full_name || row.teamId)}</td>
                  <td class="num">${row.mean_wins.toFixed(1)}</td>
                  <td class="num">
                    <div class="odds-cell">
                      <span>${(row.direct_playoff_probability * 100).toFixed(0)}%</span>
                      <div class="compare-track" style="width:60px;">
                        <div class="compare-fill home" style="width:${row.direct_playoff_probability * 100}%; background:${oddsColor};"></div>
                      </div>
                    </div>
                  </td>
                </tr>
              `;
            })
            .join("")}
        </tbody>
      </table>
      <p class="table-note"><span class="cutoff-key" aria-hidden="true"></span> Direct-playoff line: top 6 seeds</p>
    </div>
  `;
}

function playoffOddsColor(probability) {
  if (probability >= 0.75) return "var(--positive)";
  if (probability >= 0.25) return "var(--warning)";
  return "var(--text-muted)";
}

// ---------------------------------------------------------------------------
// Interaction wiring
// ---------------------------------------------------------------------------

function wireResultInteractions(resultMount, ctx) {
  if (!ctx.navigate) return;
  resultMount.querySelectorAll("[data-team-link]").forEach((el) => {
    el.addEventListener("click", () => {
      ctx.navigate("/teams", { team: el.dataset.teamLink });
    });
    // Team links are focusable (role="link"), so Enter opens them too.
    el.addEventListener("keydown", (event) => {
      if (event.key === "Enter") {
        event.preventDefault();
        ctx.navigate("/teams", { team: el.dataset.teamLink });
      }
    });
  });
}

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (c) => (
    { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]
  ));
}
