"""Regression gate over the committed validation reports in ``models/``.

Every validated number this project reports lives in a small JSON file under
``models/`` that is regenerated by a script and committed. This gate reads
those files and fails if a headline metric got worse than its recorded bound,
or if a model stopped beating the baseline it is compared against. CI runs it
on every push (it needs no data), so a change that regenerates a report with
worse numbers cannot merge quietly.

Bounds live in ``models/metric_gates.json``. A deliberate, explained change
to a bound is made with ``--update`` (records the current values plus the
tolerance) and shows up in review as a diff to that file.

    python src/metrics_gate.py            # check, exit 1 on any failure
    python src/metrics_gate.py --update   # re-record bounds from current reports
"""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODELS = ROOT / "models"
GATES_PATH = MODELS / "metric_gates.json"

# (name, report file, dotted path, direction). "lower" = lower is better.
TRACKED = [
    ("production_log_loss", "baseline_metrics.json",
     "metrics.elo_boosted_ensemble.log_loss", "lower"),
    ("production_accuracy", "baseline_metrics.json",
     "metrics.elo_boosted_ensemble.accuracy", "higher"),
    ("production_calibration_ece", "baseline_metrics.json",
     "calibration.elo_boosted_ensemble.expected_calibration_error", "lower"),
    ("margin_holdout_mae", "margin_metrics.json", "margin.holdout.selected_model.mae", "lower"),
    ("playoff_game_log_loss", "playoff_validation.json", "games.model_log_loss", "lower"),
    ("playoff_series_log_loss", "playoff_validation.json", "series.model_log_loss", "lower"),
    ("nl_success_rate", "nl_eval_report.json", "summary.success_status", "higher"),
    ("nl_grounded_rate", "nl_eval_report.json", "summary.grounded", "higher"),
    ("nl_wrong_tool_answers", "nl_eval_report.json", "summary.wrong_tool_answers", "lower"),
    ("data_check_failures", "data_checks.json", "summary.fail", "lower"),
    ("roster_moves_holdout_slope", "roster_moves_validation.json",
     "holdout_seasons.slope_through_origin", "higher"),
] + [
    (f"projection_mae_{key}", "forward_projection_backtest.json",
     f"strength_layer.summary_by_checkpoint.{key}.model_mae_wins", "lower")
    for key in ("0.00", "0.25", "0.50", "0.75")
] + [
    (f"projection_crps_{key}", "forward_projection_backtest.json",
     f"strength_layer.summary_by_checkpoint.{key}.mean_crps_wins", "lower")
    for key in ("0.00", "0.25", "0.50", "0.75")
]

# (name, report, better path, worse path): the model must beat its baseline.
MUST_BEAT = [
    ("margin_beats_home_court_constant", "margin_metrics.json",
     "margin.holdout.selected_model.mae", "margin.holdout.baseline_home_court_constant.mae"),
    ("playoff_games_beat_home_rate", "playoff_validation.json",
     "games.model_log_loss", "games.baseline_log_loss"),
    ("playoff_series_beat_higher_seed", "playoff_validation.json",
     "series.model_log_loss", "series.baseline_log_loss"),
] + [
    (f"layer_beats_frozen_crps_{key}", "forward_projection_backtest.json",
     f"strength_layer.summary_by_checkpoint.{key}.mean_crps_wins",
     f"calibrated_strength_uncertainty.summary_by_checkpoint.{key}.mean_crps_wins")
    for key in ("0.00", "0.25", "0.50", "0.75")
]

# Relative slack when recording bounds: noise from reruns (Monte Carlo seeds
# are fixed, so reruns should be exact; this only absorbs float drift).
DEFAULT_TOLERANCE = 0.005


def lookup(report, dotted):
    value = report
    for part in _split(dotted):
        value = value[part]
    return float(value)


def _split(dotted):
    # Keys like "0.00" contain dots; rejoin numeric fragments.
    parts, out = dotted.split("."), []
    index = 0
    while index < len(parts):
        part = parts[index]
        if part.isdigit() and index + 1 < len(parts) and parts[index + 1].isdigit():
            out.append(f"{part}.{parts[index + 1]}")
            index += 2
        else:
            out.append(part)
            index += 1
    return out


def load_reports(models_dir=MODELS):
    cache = {}

    def get(name):
        if name not in cache:
            cache[name] = json.loads((Path(models_dir) / name).read_text(encoding="utf-8"))
        return cache[name]
    return get


def record_bounds(models_dir=MODELS, tolerance=DEFAULT_TOLERANCE):
    get = load_reports(models_dir)
    bounds = {}
    for name, report, path, direction in TRACKED:
        value = lookup(get(report), path)
        slack = abs(value) * tolerance
        bounds[name] = {
            "report": report, "path": path, "direction": direction,
            "recorded": value,
            "bound": value + slack if direction == "lower" else value - slack,
        }
    return {"tolerance": tolerance, "bounds": bounds}


def check(gates, models_dir=MODELS):
    """Return a list of ``(name, ok, message)``."""
    get = load_reports(models_dir)
    results = []
    for name, spec in gates["bounds"].items():
        try:
            value = lookup(get(spec["report"]), spec["path"])
        except (KeyError, FileNotFoundError) as exc:
            results.append((name, False, f"missing: {spec['report']} {spec['path']} ({exc})"))
            continue
        ok = value <= spec["bound"] if spec["direction"] == "lower" else value >= spec["bound"]
        sign = "<=" if spec["direction"] == "lower" else ">="
        results.append((name, ok, f"{value:.6g} (bound {sign} {spec['bound']:.6g})"))
    tracked = {name for name, *_ in TRACKED}
    for name in sorted(tracked - set(gates["bounds"])):
        results.append((name, False, "no recorded bound; run --update and commit"))
    for name, report, better, worse in MUST_BEAT:
        try:
            a, b = lookup(get(report), better), lookup(get(report), worse)
        except (KeyError, FileNotFoundError) as exc:
            results.append((name, False, f"missing: {report} ({exc})"))
            continue
        results.append((name, a < b, f"{a:.6g} < {b:.6g}"))
    return results


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--update", action="store_true",
                        help="Re-record bounds from the current reports.")
    parser.add_argument("--tolerance", type=float, default=DEFAULT_TOLERANCE)
    args = parser.parse_args(argv)
    if args.update:
        gates = record_bounds(tolerance=args.tolerance)
        GATES_PATH.write_text(json.dumps(gates, indent=2) + "\n", encoding="utf-8")
        print(f"Recorded {len(gates['bounds'])} bounds in {GATES_PATH}")
        return 0
    gates = json.loads(GATES_PATH.read_text(encoding="utf-8"))
    results = check(gates)
    for name, ok, message in results:
        print(f"{'PASS' if ok else 'FAIL'}  {name}: {message}")
    failures = [name for name, ok, _ in results if not ok]
    print(f"{len(results) - len(failures)}/{len(results)} gates passed")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
