"""Provenance stamp for generated validation reports.

Every report under ``models/`` is regenerated by a script from local data. The
stamp records what produced it -- git commit (and whether the tree had
uncommitted changes), time, library versions, and a fingerprint of the data it
read -- so a number in a report can be traced to the code and data behind it.
"""

import datetime
import hashlib
import platform
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FEATURES_FILE = ROOT / "data" / "processed" / "game_features.csv"
DATABASE_FILE = ROOT / "data" / "database" / "nba.db"


def _git(*args):
    try:
        return subprocess.run(
            ["git", *args], cwd=ROOT, capture_output=True, text=True, timeout=10, check=True
        ).stdout.strip()
    except (OSError, subprocess.SubprocessError):
        return None


def file_fingerprint(path, hash_contents=True):
    """Size, modification time and (optionally) a short SHA-256 of a file."""
    path = Path(path)
    if not path.exists():
        return None
    stat = path.stat()
    entry = {
        "bytes": stat.st_size,
        "modified": datetime.datetime.fromtimestamp(stat.st_mtime).isoformat(timespec="seconds"),
    }
    if hash_contents:
        digest = hashlib.sha256()
        with path.open("rb") as handle:
            for chunk in iter(lambda: handle.read(1 << 20), b""):
                digest.update(chunk)
        entry["sha256_16"] = digest.hexdigest()[:16]
    return entry


def provenance():
    """The stamp: code version, environment and data fingerprint."""
    versions = {"python": platform.python_version()}
    for module in ("numpy", "pandas", "sklearn"):
        try:
            versions[module] = __import__(module).__version__
        except ImportError:  # pragma: no cover
            versions[module] = None
    status = _git("status", "--porcelain", "--untracked-files=no")
    return {
        "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "git_commit": _git("rev-parse", "HEAD"),
        "git_dirty": None if status is None else bool(status),
        "versions": versions,
        "data": {
            # The 1 GB database is fingerprinted by size/mtime only.
            "game_features.csv": file_fingerprint(FEATURES_FILE),
            "nba.db": file_fingerprint(DATABASE_FILE, hash_contents=False),
        },
    }


def with_provenance(report):
    """``report`` with a ``provenance`` key added (dict reports only)."""
    if not isinstance(report, dict):
        return report
    return {**report, "provenance": provenance()}
